Bug fix: gpt-4-base runs with ChatCompletion (#1300)
If you run an eval with `gpt-4-base` you get the following error:
```
openai.error.InvalidRequestError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?
```

Example: run `oaieval gpt-4-base,gpt-4 multiturn` on
[commit](https://github.com/openai/evals/commit/413402ecc5115a21710acbd4b844c3668052c874)

---

With this fix, you can run evals with `gpt-4-base` without the error. 

Example: run `oaieval gpt-4-base,gpt-4`
[commit](https://github.com/openai/evals/commit/e1230bdd82e15a4eeaea5f7ae726924bab72631d)