improve error message on jsonl parsing errors (#259)
This pull request improves the error messages in case of parsing
failures on the jsonl test files. Currently it is quite cryptic, with a
misleading message about the failure being on line number 1.

```
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 5338 (char 5337)
```

In this particular case, it turned out the error was actually on line
143!


With this commit, it should now give a much nicer message:
```
ValueError: Error parsing JSON on line 143: Expecting ',' delimiter at decompilation-func-recovery/samples-x86-musl.jsonl:143:5338
```