[bugfix] Fix a bug in --registry_path handling (#1101)
A bug in the handling of `--registry_path` was introduced in
https://github.com/openai/evals/pull/1036/files#diff-a694333152a5a73db19b8951647e60aed78f43fec6b119707bc6d489289be6c0R87

To repro, run the example from
https://github.com/openai/evals/blob/main/examples/retrieval-completionfn.ipynb

Before the fix, the following exception will be thrown
```
TypeError: unsupported operand type(s) for /: 'list' and 'str'
```